### ISSUE TITLE
How to create features for multiple datetime columns?

### ISSUE THREAD

**Issue by dehiker** [alteryx/featuretools#2321] opened 2022-10-09 07:32 UTC
Sorry to put three question in one issue, but I tried not to bother you too much.

1. How to **create features for multiple datatime columns**?
I got a dataframe with multiple datetime columns, and hoped to create features like TimeSinceFirst, TimeSinceLast for all of them. But with only one of them set as time_index, I couldn't get time-related features for the others with DFS.
I found a related post on SO, which seems deprecated: [FeatureTools: Can there be multiple columns in time_index parameters?](https://stackoverflow.com/questions/58156703/featuretools-can-there-be-multiple-columns-in-time-index-parameters)

2. Is there any (performance) difference between **DFS and calculate_feature_matrix**?
While I got to do DFS for different entitysets of the same structure, is there any preference for the following two methods:
    - Just DFS repeatedly;
    - DFS and save feature definitions for the frist time, and then calculate_feature_matrix with saved definitions for the following entitysets.

3. Why couldn't I **suppress RuntimeWarning** when DFS, and how to make it?
Tons of RuntimeWarning printed when running
```
with warnings.catch_warnings():
    warnings.simplefilter(action="ignore", category=RuntimeWarning)
    ft.dfs(...)
```
```
/.../python3.9/site-packages/numpy/lib/nanfunctions.py:1117: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
```

Any idea is highly appreciated! Best regards!

**Comment by ozzieD** [comment] 2022-10-12 22:34
Hello @dehiker,

1. You can create features for multiple datatime columns as long as the chosen primitives are not relying on a `time_index` being set. You are correct in implying the SO link above being deprecated. Since then, featuretools started using [woodwork](https://featuretools.alteryx.com/en/stable/getting_started/woodwork_types.html) for typing. Unfortunately, you can only set one time_index per df. If you want primitives like`TimeSinceFirst` to work with no time_index, the best course of action would probably be to create a custom version of that primitive that accepts all Datetime types and will handle sorting. 

2. The second one will be preferred since you don't have to go through building feature definitions again, as long as you have the same entityset schema. We did make a change not too long ago to make `build_features` more performant (https://github.com/alteryx/featuretools/pull/2224) in dfs so ideally the first option wouldn't take _that_ much longer. 

3. I'm not able to reproduce those specific warnings unfortunately so I'm not sure what's going on there. Is it happening with a specific primitive?

**Comment by dehiker** [comment] 2022-10-14 08:12
Awesome, thanks a lot @ozzieD 
1. I'll try to create a custom primitive for datetime. It would be helpful If you got some demo on this.
2. Gotcha, I'll take the 2nd.
3. Just found "median" primitive cause the RuntimeWarning. Maybe warning setting reset in the primitive?

**Comment by gsheni** [comment] 2022-10-14 13:57
@dehiker 
1. You can follow the defining custom primitives guide in our [documentation](https://featuretools.alteryx.com/en/stable/getting_started/primitives.html#Defining-Custom-Primitives)

3. Our Median primitive, just uses the pandas `median` function, so I am not sure how this could be causing a warning. See [source code](https://github.com/alteryx/featuretools/blob/c73c3514aedf8fa1b2d3f361f72abd8a016ae167/featuretools/primitives/standard/aggregation_primitives.py#L474). Do you have NaNs in your Integer/Double columns?

**Comment by dehiker** [comment] 2022-10-15 13:48
Thanks for your prompt reply, @gsheni 

As to the warning, yeah, I think there're NaNs, though I could not confirm it because breakpoint at nanops.py:754 didn't get hit (don't why).
And after raising the warning, I got stack info like below, which may be helpful. I'm also curious why there's no stack info for aggregation_primitives.py in which Median primitive defined.

Best regards!

<details>
...
    feature_matrix_, _ = ft.dfs(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/utils/entry_point.py", line 39, in function_wrapper
    raise e
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/utils/entry_point.py", line 32, in function_wrapper
    return_value = func(*args, **kwargs)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/synthesis/dfs.py", line 283, in dfs
    feature_matrix = calculate_feature_matrix(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 316, in calculate_feature_matrix
    feature_matrix = parallel_calculate_chunks(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 855, in parallel_calculate_chunks
    results = client.gather(batch)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/distributed/client.py", line 2175, in gather
    return self.sync(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/distributed/client.py", line 2038, in _gather
    raise exception.with_traceback(traceback)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/dask/utils.py", line 41, in apply
    return func(*args, **kwargs)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 536, in calculate_chunk
    _feature_matrix = calc_results(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/utils.py", line 43, in wrapped
    r = method(*args, **kwargs)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 506, in calc_results
    matrix = calculator.run(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/feature_set_calculator.py", line 121, in run
    self._calculate_features_for_dataframe(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/feature_set_calculator.py", line 365, in _calculate_features_for_dataframe
    df = self._calculate_features(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/feature_set_calculator.py", line 385, in _calculate_features
    df = handler(group, df, df_trie, progress_callback)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/feature_set_calculator.py", line 812, in _calculate_agg_features
    to_merge = base_frame.groupby(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 890, in aggregate
    result = op.agg()
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/apply.py", line 169, in agg
    return self.agg_dict_like()
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/apply.py", line 486, in agg_dict_like
    results = {
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/apply.py", line 487, in <dictcomp>
    key: obj._gotitem(key, ndim=1).agg(how) for key, how in arg.items()
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 282, in aggregate
    ret = self._aggregate_multiple_funcs(func)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 337, in _aggregate_multiple_funcs
    results[key] = self.aggregate(func)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 298, in aggregate
    return self._python_agg_general(func, *args, **kwargs)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/groupby.py", line 1665, in _python_agg_general
    result = self.grouper.agg_series(obj, f)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/ops.py", line 1073, in agg_series
    result = self._aggregate_series_pure_python(obj, func)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/ops.py", line 1105, in _aggregate_series_pure_python
    res = func(group)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/groupby.py", line 1651, in <lambda>
    f = lambda x: func(x, *args, **kwargs)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/generic.py", line 11926, in median
    return NDFrame.median(self, axis, skipna, level, numeric_only, **kwargs)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/generic.py", line 11420, in median
    return self._stat_function(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/generic.py", line 11360, in _stat_function
    return self._reduce(
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/series.py", line 4800, in _reduce
    return delegate._reduce(name, skipna=skipna, **kwds)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/arrays/masked.py", line 1057, in _reduce
    result = op(data, axis=0, skipna=skipna, mask=mask, **kwargs)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/nanops.py", line 153, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/nanops.py", line 793, in nanmedian
    res = get_median(values) if notempty else np.nan
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/nanops.py", line 754, in get_median
    res = np.nanmedian(x[mask])
  File "<__array_function__ internals>", line 5, in nanmedian
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/numpy/lib/nanfunctions.py", line 1117, in nanmedian
    return np.nanmean(a, axis, out=out, keepdims=keepdims)
  File "<__array_function__ internals>", line 5, in nanmean
  File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/numpy/lib/nanfunctions.py", line 954, in nanmean
    warnings.warn("Mean of empty slice", RuntimeWarning, stacklevel=3)
RuntimeWarning: Mean of empty slice
</details>

**Comment by ozzieD** [comment] 2022-10-17 18:42
There isn't stack info for `aggregation_primitives.py` because in `_calculate_agg_features` in `featuretools/computational_backends/feature_set_calculator.py` line 781 `agg_wrapper` is grabbing the get_function() to apply. It looks like we do see the stack info pointing to median in your log. 

`File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/feature_set_calculator.py", line 812, in _calculate_agg_features to_merge = base_frame.groupby( File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 890, in aggregate result = op.agg()`

It looks like this line is the cause of the warning. I'd set the breakpoint here and see what you can find in your environment.

**Comment by dehiker** [comment] 2022-10-19 04:18
@ozzieD @gsheni Thank you for your advice.

1. Sadly, the breakpoint didn't get hit either
`b /home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/generic.py:890`

2. After reading recommended doc, and source code of `class TimeSinceLast(AggregationPrimitive):`, I've no idea how to implement a custom primitive which would be **different from built-in one but work for no time_index columns**.
Why would built-in one not work for no time_index? And how to make it in custom implementation?

And ideas are highly appreciated!

**Comment by ozzieD** [comment] 2022-10-19 21:21
For the custom primitive you could copy all of `TimeSinceLast` and just remove `semantic_tags={"time_index"}` from `input_types = [ColumnSchema(logical_type=Datetime, semantic_tags={"time_index"})]`. When this is removed from your custom TimeSinceLast primitive it will run on all DateTime columns instead of only one which was previously specified as the `time_index`. As mentioned above there is only one `time_index` per df.  `time_index` is meant to signify ordering on that datetime field.

**Comment by dehiker** [comment] 2022-10-21 07:53
Now the custom primitives work like a charm! Thank you so much @ozzieD

**Comment by ozzieD** [comment] 2022-10-24 16:49
@dehiker awesome to hear! I'm going to close this issue for now.

**Closed by ozzieD** 2022-10-24 16:49 UTC
