### ISSUE TITLE
datetime.date in utils.wrangle._check_time_type 

### ISSUE THREAD

**Issue by RogerTangos** [alteryx/featuretools#150] opened 2018-05-15 14:46 UTC
Should the [utils.wrangle._check_time_type](https://github.com/Featuretools/featuretools/blob/master/featuretools/utils/wrangle.py#L165) include checking for `datetime.date`? If so, would you mind if I made a PR for it?

I apologize if this is a naive question. I recently began working with a not-quite-complete demo notebook from someone in Kalyan's group, and this is my first time working with FeatureTools. Right now, the demo is throwing `ValueError`s after sending `datetime.date`objects to `_check_time_type`,  and I'm not sure whether this error is with the demo or with the library. (It does seem to run without errors when I make the suggested fix.)

If this is better asked on StackOverflow, please let me know, and I'll move the question there.

**Comment by anordin95** [comment] 2018-05-15 15:07
I don't run into this bug when I run the demos. I agree there could be more types for time type checking in the function check_time_type, but I'll also push my most recent demos code to Trane-Aux for you.

**Comment by tamargrey** [comment] 2022-03-11 15:32
Investigating whether this issue is still relevant with ft 1.0 and later (@gsheni):

Previously `_check_time_type` was used in two contexts:

1. confirming a time index/secondary time index was the same time type as the rest of an entityset when setting a time index
2. confirming a cutoff time is the same time type as the time type of the entityset in CFM.

With the featuretools 1.0 woodwork integration, the first use is now handled by Woodwork, since any dataframe with Woodwork types will have its datetime columns standardized to the same physical types. Woodwork recognizes datetime columns with its [col_is_datetime](https://github.com/alteryx/woodwork/blob/main/woodwork/type_sys/utils.py#L13) util that has a similar ` isinstance(time, datetime)` call. In addition to that, though, it also attempts to change the type `to_datetime` and treats an exception during that conversion as proof that the column is not datetime in nature. It's possible that the second part of this util is why we've never run into a reason to add `date` (or even `np.datetime64`) to this check--I don't remember but maybe @thehomebrewnerd does? It might be worth investigating if adding either of those could improve woodwork's datetime inference. 

The second use of `_check_time_type` in Featuretools' `_check_cutoff_time_type` has stayed roughly the same in the featuretools 1.0 integration. If the cutoff time is defined in a tuple, we check the time type of that individual value. Because of that, the bug seen in this issue could still be present. We have no reproducible example of this bug, so we can either proceed in one of two ways in Featuretools:
1. Investigate the addition of `date` into `_check_time_type` and see if we can reproduce the error or, at the very least, confirm it doesn't making the time type check worse. 

This still leaves the single cutoff time type check using slightly different "is datetime" logic than that of Woodwork, so we can also do:
2. Add the single time type into a series and use Woodwork's type inference to check if `is_datetime` or `is_numeric`, causing all of our time type checking to use the same logic. This would then benefit from investigating the inclusion of `date` into the `col_is_datetime` woodwork util.

**Comment by tamargrey** [comment] 2022-03-15 22:38
Closing in favor of #1965 and https://github.com/alteryx/woodwork/issues/1341

**Closed by tamargrey** 2022-03-15 22:38 UTC
