### ISSUE TITLE
Support Spark using Koalas dataframes

### ISSUE THREAD

**Issue by rwedge** [alteryx/featuretools#887] opened 2020-04-10 20:49 UTC
Created a separate issue to discuss / track idea brought up in #203 by @candalfigomoro

more info on Koalas: https://github.com/databricks/koalas

**Comment by candalfigomoro** [comment] 2020-04-16 10:23
The "make_index" strategy implemented for Dask dataframes (https://github.com/FeatureLabs/featuretools/pull/783/commits/e6d2418b49fd4f31c51d85b489e7465e07cedc15#diff-a155fbecaa281b97fe92d12c2c458342R565) is not good for Koalas/Spark.

While you could use `.cumsum()` in Koalas, it relies on a Spark's Window (see https://github.com/databricks/koalas/blob/bba7623318fcedbdc7aa9dadf37a6d164bb5f2d7/databricks/koalas/generic.py#L184) so it does not scale to large datasets (you'll get OOM errors).

Here you can find an explanation for alternatives: https://github.com/databricks/koalas/blob/master/docs/source/user_guide/options.rst#default-index-type

**Comment by Tagar** [comment] 2020-06-19 17:42
@candalfigomoro with Koalas 1.0 release that improves a bunch of APIs, 
do you think it's easier to make FT on Koalas work? 

I didn't exactly follow the make_index issue - if it's still not possible with Koalas 1.0, I can have a look what are the options there. Do you mind explaining what would be the required functionality in Koalas to make Feature Tools work on Koalas? 

Thanks

**Comment by candalfigomoro** [comment] 2020-06-24 10:52
I see there's a pending PR for Koalas support: https://github.com/FeatureLabs/featuretools/pull/1031

**Comment by candalfigomoro** [comment] 2020-06-24 11:06
@Tagar 

> I didn't exactly follow the make_index issue - if it's still not possible with Koalas 1.0, I can have a look what are the options there. 

In order to create an index (make_index), the Dask implementation uses the following trick:

```
df[index] = 1
df[index] = df[index].cumsum() - 1
```
It adds a constant column with value=1, then it uses the cumsum() method to generate the incremental values (by cumulatively summing ones).

I don't know if this scales well in Dask, but it does not scale in Spark, see the "Note" box here: https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.DataFrame.cumsum.html#databricks.koalas.DataFrame.cumsum

So make_index should be implemented in another way (instead of using the cumsum() trick). Maybe we could rely on the reset_index() method.

**Comment by Tagar** [comment] 2020-06-24 21:30
@candalfigomoro @tuethan1999  
Does the index has to be deterministic? Does it have to be sequential? 
If answers are "no" to both, then `distributed` would be the most performant way to generate an index in Spark/Koalas:

> **distributed**: It implements a monotonically increasing sequence simply by using PySpark's monotonically_increasing_id function in a fully distributed manner. The values are indeterministic. If the index does not have to be a sequence that increases one by one, this index should be used. Performance-wise, this index almost does not have any penalty comparing to other index types. See the example below:

```
>>> import databricks.koalas as ks
>>> ks.set_option('compute.default_index_type', 'distributed')
>>> kdf = ks.range(3)
>>> ks.reset_option('compute.default_index_type')
>>> kdf.index
Int64Index([25769803776, 60129542144, 94489280512], dtype='int64')
```

Internally `distributed` indexing uses `monotonically_increasing_id` 
https://spark.apache.org/docs/2.4.6/api/python/pyspark.sql.html#pyspark.sql.functions.monotonically_increasing_id

> A column that generates monotonically increasing 64-bit integers.
> 
> The generated ID is guaranteed to be monotonically increasing and unique, but not consecutive. The current implementation puts the partition ID in the upper 31 bits, and the record number within each partition in the lower 33 bits. The assumption is that the data frame has less than 1 billion partitions, and each partition has less than 8 billion records.
> 
> Note The function is non-deterministic because its result depends on partition IDs.
>

**Comment by candalfigomoro** [comment] 2020-06-25 09:31
I don't know if it needs to be sequential, we should ask this to someone with a good knowledge of the FT code. If it doesn't have to be sequential, "distributed" (based on monotonically_increasing_id() ) would be the most performant choice. If it needs to be sequential, we could use "distributed-sequence" which is the default type in recent Koalas version afaik. Both options would be an improvement over the "cumsum" trick, which collects everything in a single node.

**Comment by thehomebrewnerd** [comment] 2020-06-25 12:52
> I don't know if it needs to be sequential, we should ask this to someone with a good knowledge of the FT code. If it doesn't have to be sequential, "distributed" (based on monotonically_increasing_id() ) would be the most performant choice. If it needs to be sequential, we could use "distributed-sequence" which is the default type in recent Koalas version afaik. Both options would be an improvement over the "cumsum" trick, which collects everything in a single node.

The index column for a Featuretools entity does not need to be sequential, but it should be unique.

**Comment by candalfigomoro** [comment] 2020-06-25 13:26
I think we could use the `attach_distributed_column` function, see https://github.com/databricks/koalas/blob/master/databricks/koalas/internal.py#L563

**Comment by candalfigomoro** [comment] 2020-06-25 15:40
Using `attach_distributed_column` has 2 problems:

1.  You need to modify the underlying Spark dataframe
2.  It's an internal method and we are not supposed to use it

We could try something like this (it's a bit hacky but it should work):
```
# kdf is our Koalas dataframe
# index is the name of the id column we want to create

original_columns = kdf.columns.tolist()  # list of original koalas dataframe columns
original_index_names = kdf.index.names  # list of original koalas dataframe index names
kdf = kdf.reset_index()  # reset_index moves original indexes to columns and creates an increasing id
new_columns = kdf.columns.tolist()  # list of new koalas dataframe columns (with the original indexes as columns)
new_index_names = [col for col in new_columns if col not in original_columns]  # column names of the original indexes
kdf = kdf.reset_index()  # the increasing id we created before becomes a simple column called "index"
kdf = kdf.set_index(new_index_names)  # restore the original indexes
kdf.index.names = original_index_names  # restore the original index names
kdf = kdf.rename(columns={"index": index})  # rename the index column with the name of the index parameter we set
```

**Comment by Tagar** [comment] 2020-06-25 15:53
> The index column for a Featuretools entity does not need to be sequential, but it should be unique.

`monotonically_increasing_id()` is guaranteed to be unique. 

Why something simple like this wouldn't work then - 

```python
>>> ks.set_option('compute.default_index_type', 'distributed')
>>> kdf = ks.range(3)
>>> ks.reset_option('compute.default_index_type')
```

**Comment by candalfigomoro** [comment] 2020-06-25 16:04
Using the default index would work, but my understanding was (I could be wrong btw) that FT needs an "index" column which is not the dataframe index, so the only purpose of the workaround above is to "move" a default index generated by Koalas to a simple dataframe column. Can we use the dataframe index instead of defining a column as index?

**Comment by ueshin** [comment] 2020-06-25 16:26
Hi, thanks for your interests in Koalas!

If you requirement is:

> The index column for a Featuretools entity does not need to be sequential, but it should be unique.

I'd suggest to use `F.monotonically_increasing_id()` directly:

```py
from pyspark.sql import functions as F

kdf['index'] = F.monotonically_increasing_id()
```

Also,

> Can we use the dataframe index instead of defining a column as index?

If you can use the dataframe index, I'd suggest:

```py
with ks.option_context("compute.default_index_type", "distributed"):
    kdf.reset_index()
```

If you don't need the original index, you can specify `drop=True`; `kdf.reset_index(drop=True)`.

**Comment by candalfigomoro** [comment] 2020-06-25 17:09
@ueshin 

> ```python
> from pyspark.sql import functions as F
> 
> kdf['index'] = F.monotonically_increasing_id()
> ```

I didn't know it was possible to assign it this way, nice! Thank you!

Because in general (not in this case) we could want sequential ids, I also issued the following suggestion: https://github.com/databricks/koalas/issues/1612

**Comment by Tagar** [comment] 2020-06-25 20:52
@candalfigomoro thanks - didn't realize `index` column had to be "outside" of the df index column.. just for understanding - what are the use cases for sequential ids in FT? 

@thehomebrewnerd thanks for confirming that the only requirement is for the index is to be unique

thanks @ueshin 

@tuethan1999 can you amend the PR using the approach @ueshin has described? thx!

**Comment by candalfigomoro** [comment] 2020-06-30 09:12
> @candalfigomoro thanks - didn't realize `index` column had to be "outside" of the df index column.. just for understanding - what are the use cases for sequential ids in FT?

I think @thehomebrewnerd is more suitable than me for this kind of questions :)

**Comment by candalfigomoro** [comment] 2020-06-30 09:12
We should add Koalas as a soft dependency (not a hard one), see https://github.com/FeatureLabs/featuretools/issues/1037

**Comment by thehomebrewnerd** [comment] 2020-06-30 15:29
> > @candalfigomoro thanks - didn't realize `index` column had to be "outside" of the df index column.. just for understanding - what are the use cases for sequential ids in FT?
> 
> I think @thehomebrewnerd is more suitable than me for this kind of questions :)

There isn't really a specific use case for the index column to be sequential. This column is just a unique identifier for the row. Many data sets have this unique id column already in place, so we can often use that instead of creating the column.

For the sake of reproducibility, if we are making an index column for an Entity, the process should be deterministic. If the process is not deterministic, making the entity multiple times from the same set of data could result in different underlying dataframes as the index columns might not be the same. Non-deterministic index columns could also result in unit testing issues, if we don't get the same values every time we run.

**Comment by Tagar** [comment] 2020-07-28 18:18
@thehomebrewnerd sorry for the delay in response 

One way to make a column deterministic is to have it defined as something like `key_column = hash(list_of_key_columns)` or `key_column = concat(list_of_key_columns)` 

As for the unit tests - most of them are defined on smaller datasets which would work fine as a Spark dataframe with a single partition. In that case `monotonically_increasing_id` is deterministic when there is just one partition. 

@ueshin any thoughts on this? thanks.

**Comment by Tagar** [comment] 2020-07-29 04:12
Just to clarify - `list_of_key_columns` is whatever makes a primary key for a given dataset (provided by the user). 

One another option is to do something like 
```python
F.hash(F.col("*")) 
```
or 
```python
F.hash("*")
```

so PySpark would hash all the columns in a dataset (might be okay in some cases, but generally not recommended for wider datasets or for datasets with large string/binary columns due to performance concerns). 

`F.monotonically_increasing_id()` would still be a safer and generally a better option; perhaps FT should just documented its non-deterministic nature in a distributed environment, and provide an option to explicitly specify key column(s).

**Comment by candalfigomoro** [comment] 2020-07-29 09:57
With `koalas >= 1.1.0` we can use the `attach_id_column` method to add the index column (although it can be "non-deterministic").

**Comment by thehomebrewnerd** [comment] 2020-07-29 12:28
> `F.monotonically_increasing_id()` would still be a safer and generally a better option; perhaps FT should just documented its non-deterministic nature in a distributed environment, and provide an option to explicitly specify key column(s).

Just one point for clarification here. Featuretools already has the ability to use an existing column for the index (but that column should be unique), and in that case no new columns will be created. We only need to create this index column in situations where the underlying dataframe does not already contain a unique index column.

**Comment by Tagar** [comment] 2020-07-29 17:35
@candalfigomoro `attach_id_column` uses `monotonically_increasing_id` under the hood 
https://github.com/databricks/koalas/blob/8d65308c43489f662a40d7c17a0cd9c6149ba00e/databricks/koalas/internal.py#L626 so it has the same semantic. 

@thehomebrewnerd that's great Featuretools already has capability to use an existing column for the index! 

I see there newer commits from @frances-h on https://github.com/FeatureLabs/featuretools/pull/1031 - hope to see Koalas support soon! 

Thanks everyone

**Comment by Tagar** [comment] 2020-08-13 17:52
Hot off the press @ueshin and team's article about Koalas - it covers nicely some of the items we discussed here 

https://databricks.com/blog/2020/08/11/interoperability-between-koalas-and-apache-spark.html 

Particularly, different provided indexing strategies (if an index column isn't already part of a dataset) - 
 
<img width="1055" alt="Screen Shot 2020-08-13 at 11 50 40 AM" src="https://user-images.githubusercontent.com/3013418/90169161-769d3c80-dd5b-11ea-8e21-47461b452966.png">

**Comment by Tagar** [comment] 2020-09-08 23:27
https://github.com/FeatureLabs/featuretools/releases/tag/v0.19.0 
release 0.19 includes support for Koalas 🎉

**Comment by thehomebrewnerd** [comment] 2024-05-10 15:06
Pyspark support is being dropped

**Closed by thehomebrewnerd** 2024-05-10 15:06 UTC
